-- MySQL Script generated by MySQL Workbench
-- Thu May 12 22:32:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema plataforma_upro
-- -----------------------------------------------------
-- Base de datos para la plataforma UPRO
-- 

-- -----------------------------------------------------
-- Schema plataforma_upro
--
-- Base de datos para la plataforma UPRO
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `plataforma_upro` ;
USE `plataforma_upro` ;

-- -----------------------------------------------------
-- Table `plataforma_upro`.`type_contact_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`type_contact_information` (
  `type_contact_information_id` INT NOT NULL AUTO_INCREMENT,
  `type_contact_information_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`type_contact_information_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`contact_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`contact_information` (
  `contact_information_id` INT NOT NULL AUTO_INCREMENT,
  `type_contact_information_id` INT NOT NULL,
  `contact_information_desc` VARCHAR(255) NULL,
  PRIMARY KEY (`contact_information_id`, `type_contact_information_id`),
  INDEX `fk_contact_information_type_contact_information_idx` (`type_contact_information_id` ASC) ,
  CONSTRAINT `fk_contact_information_type_contact_information`
    FOREIGN KEY (`type_contact_information_id`)
    REFERENCES `plataforma_upro`.`type_contact_information` (`type_contact_information_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`document_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`document_type` (
  `document_type_id` INT NOT NULL,
  `document_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`document_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`document` (
  `document_id` INT NOT NULL,
  `document_desc` VARCHAR(80) NULL,
  `document_type_id` INT NOT NULL,
  PRIMARY KEY (`document_id`, `document_type_id`),
  INDEX `fk_document_document_type1_idx` (`document_type_id` ASC) ,
  CONSTRAINT `fk_document_document_type1`
    FOREIGN KEY (`document_type_id`)
    REFERENCES `plataforma_upro`.`document_type` (`document_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`gender` (
  `gender_id` INT NOT NULL AUTO_INCREMENT,
  `gender_desc` VARCHAR(100) NULL,
  PRIMARY KEY (`gender_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `person_names` VARCHAR(120) NULL,
  `person_lastname` VARCHAR(120) NULL,
  `person_bith_date` DATE NULL,
  `contact_information_id` INT NOT NULL,
  `document_id` INT NOT NULL,
  `gender_id` INT NOT NULL,
  PRIMARY KEY (`person_id`, `contact_information_id`, `document_id`),
  INDEX `fk_person_contact_information1_idx` (`contact_information_id` ASC) ,
  INDEX `fk_person_document1_idx` (`document_id` ASC) ,
  INDEX `fk_person_gender1_idx` (`gender_id` ASC) ,
  CONSTRAINT `fk_person_contact_information1`
    FOREIGN KEY (`contact_information_id`)
    REFERENCES `plataforma_upro`.`contact_information` (`contact_information_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_document1`
    FOREIGN KEY (`document_id`)
    REFERENCES `plataforma_upro`.`document` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_gender1`
    FOREIGN KEY (`gender_id`)
    REFERENCES `plataforma_upro`.`gender` (`gender_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`user_type` (
  `user_type_id` INT NOT NULL,
  `user_type_desc` VARCHAR(45) NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_username` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_token` VARCHAR(255) NULL,
  `user_type_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `person_id`),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC) ,
  INDEX `fk_user_user_type1_idx` (`user_type_id` ASC) ,
  INDEX `fk_user_person1_idx` (`person_id` ASC) ,
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `plataforma_upro`.`user_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `plataforma_upro`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`option` (
  `option_id` INT NOT NULL AUTO_INCREMENT,
  `option_desc` VARCHAR(45) NULL,
  `option_url` VARCHAR(45) NULL,
  `option_icon` VARCHAR(45) NULL,
  PRIMARY KEY (`option_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`action` (
  `action_id` INT NOT NULL AUTO_INCREMENT,
  `action_desc` VARCHAR(255) NULL,
  `action_url` VARCHAR(255) NULL,
  `option_id` INT NOT NULL,
  PRIMARY KEY (`action_id`, `option_id`),
  INDEX `fk_action_option1_idx` (`option_id` ASC) ,
  CONSTRAINT `fk_action_option1`
    FOREIGN KEY (`option_id`)
    REFERENCES `plataforma_upro`.`option` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`action_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`action_has_user` (
  `action_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`action_id`, `user_id`),
  INDEX `fk_action_has_user_user1_idx` (`user_id` ASC) ,
  INDEX `fk_action_has_user_action1_idx` (`action_id` ASC) ,
  CONSTRAINT `fk_action_has_user_action1`
    FOREIGN KEY (`action_id`)
    REFERENCES `plataforma_upro`.`action` (`action_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_action_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `plataforma_upro`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`user_has_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`user_has_option` (
  `user_id` INT NOT NULL,
  `option_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `option_id`),
  INDEX `fk_user_has_option_option1_idx` (`option_id` ASC),
  INDEX `fk_user_has_option_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_option_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `plataforma_upro`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_option_option1`
    FOREIGN KEY (`option_id`)
    REFERENCES `plataforma_upro`.`option` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`institution` (
  `institution_id` INT NOT NULL AUTO_INCREMENT,
  `institution_desc` VARCHAR(255) NULL,
  PRIMARY KEY (`institution_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`education_achieved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`education_achieved` (
  `education_achieved_id` INT NOT NULL AUTO_INCREMENT,
  `education_achieved_desc` VARCHAR(45) NULL,
  `institution_id` INT NOT NULL,
  PRIMARY KEY (`education_achieved_id`, `institution_id`),
  INDEX `fk_education_achieved_institution1_idx` (`institution_id` ASC),
  CONSTRAINT `fk_education_achieved_institution1`
    FOREIGN KEY (`institution_id`)
    REFERENCES `plataforma_upro`.`institution` (`institution_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `plataforma_upro`.`person_has_education_achieved`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `plataforma_upro`.`person_has_education_achieved` (
  `person_id` INT NOT NULL,
  `education_achieved_id` INT NOT NULL,
  PRIMARY KEY (`person_id`, `education_achieved_id`),
  INDEX `fk_person_has_education_achieved_education_achieved1_idx` (`education_achieved_id` ASC) ,
  INDEX `fk_person_has_education_achieved_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_person_has_education_achieved_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `plataforma_upro`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_has_education_achieved_education_achieved1`
    FOREIGN KEY (`education_achieved_id`)
    REFERENCES `plataforma_upro`.`education_achieved` (`education_achieved_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
